print("ejercicio 1")
texto = (input("ingrese un texto: "))
mi_pila = list(texto)
print(mi_pila)
pila_invertida = ""
for caracter in mi_pila[::-1]:
   pila_invertida = pila_invertida+caracter
print(pila_invertida)
print()
print("ejercico 2")
from collections import deque
cola = deque()
cola.append("AGUAS LEYVA SHERING")
cola.append("OSORIO FERNANDEZ MARIA")
cola.append("VALERA JIMENEZ EDUARDO")
cola.append("REGALAO ROYERO YANNIER")
cola.append("CORONADO ALBOR JESUS")
cola.append("RUIZ CHAMORRO OSCAR")
cola.append("MENDEZ RUIZ BRIAN")
cola.append("FERRER PALENCIA JUAN")
cola.append("MARQUEZ BONIFACIO ANNETH")
cola.append("GUTIERREZ DUQUE JUAN DAVID")
cola.append("ALDANA NORIEGA MAURICIO")
cola.append("SOLANO MARENCO JESSYCA")
cola.append("ESCAMILLA MOLINA JOSE")
cola.append("GUTIERREZ RODRIGUEZ JOSE")
cola.append("HERRERA QUESADA INES")
cola.append("MIRANDA GANDO YURLEYRIS")
cola.append("RUA ARZUZA JUAN")
cola.append("ALVAREZ PINO SANTIAGO")
cola.append("ADALBERTO ALBONIS VAQUERO")
cola.append("DIAZ DIAZ KARLA")
cola.append("ROJAS ORTEGA ABEL")
cola.append("YO")
cola.append("SORIANO ARIAS JUAN PABLO")
cola.append("GRANADOS PUELLO ANDRES ")
cola.append("CONTRERAS NAVARRO FREDYS")
cola.append("PION GUZMAN CARLOS")
cola.append("REBOLLEDO HERNANDEZ LUIS")
cola.append("ZABALETA BLANQUICETT ADALBERTO")
cola.append("BARCELO AGUILAR SEBASTIAN")
cola.append("GONZALEZ PUERTA JHOINER")
cola.append("JIMENEZ FONTALVO PEDRO")
cola.append("ALVAREZ MONTES DANIEL")
cola.append("CAMACHO LOPEZ VALERITH")
cola.append("TAPIA MONTES LINA")
cola.append("BARLIZA REDONDO MARIA")
print(cola)
orden = sorted(cola)
for i in orden:
    print(i)